### ISSUE TITLE
As a user, I want a list of possible travel routes so I can pick my preferred route

### ISSUE THREAD

**Issue by felixlapierre** [felixlapierre/campus-guide#11]
**Acceptance Criteria**
Given that I am on the directions page,
And that I have selected the Bus routes option,
Then I should see different possible travel routes to choose from (a recommended route, a route with least walking, and a route with fewest transfers).

**Comment by jun-loke** [comment]
Needs clarification: description unclear

**Comment by jun-loke** [comment]
Multiple routes per vehicle choice
![image.png](https://images.zenhubusercontent.com/5e15dd2d736ad30422392a16/5abda067-9801-47ab-af0a-ba9573152126)
