### ISSUE TITLE
Quality Report

### ISSUE THREAD

**Issue by sharon-ho** [felixlapierre/campus-guide#113]
- You must have SonarQube installed at this point.
- Report metrics related to code duplication, code documentation, size, coupling, cohesion (coupling and cohesion are available only for object-oriented languages)
- Report the code smells or technical debt detected by the tool
- Describe your strategies to improve the metrics
- Comparison with previous metrics (metrics evolution) [optional for Sprint #3, only if you have metrics from Sprint #2, mandatory for Sprint #4]

**Comment by FGRCL** [comment]
SonarQube doesn't seem to be able to generate cohesion and coupling metric for Kotlin projects. Furthermore, the teacher asked for "Code Documentation" metrics, I'll assume that it means the Comment Lines and Comment (%) metric.
