### ISSUE TITLE
Acceptance Criteria for Product Owner

### ISSUE THREAD

**Issue by sharon-ho** [felixlapierre/campus-guide#115]
You will make your acceptance tests as Issues in your GitHub Issue Tracker and the Product Owner will be able to add his comments and sign with his own GitHub account. Please make a special label for acceptance tests, so that it is easy to distinguish them from the other issues.

**User Stories:**
- #3
- #7
- #10
- #15
- #16
- #18
- #29
- #49

**Not Part of Sprint 3**
- #9

**Comment by felixlapierre** [comment]
Reviewed, they all look good, thanks for including video demonstrations too!
