### ISSUE TITLE
Start and destination marker titles are coordinate points instead of the names of the locations

### ISSUE THREAD

**Issue by sharon-ho** [felixlapierre/campus-guide#124]
**Steps to reproduce:**
1. Click on the navigation button
2. Enter any start location and destination using the "Search for Location" method
3. Observe the start and destination names and their marker titles on the route displayed on the map

**Expected:**
- Names of the start and destination and their marker titles should be the names of the locations submitted and not the LatLng coordinate points

**Actual:**
- Names of the start and destination and their marker titles are their LatLng coordinate points

**Screenshot:**
![Screenshot_20200329-022151.png](https://images.zenhubusercontent.com/5e1cf02ce040605817d94ec2/5d20caf0-baf7-4acf-92de-1b514dee89e8)

**Comment by felixlapierre** [comment]
I had to fix this as part of doing #20, will be fixed once that is merged

**Comment by sharon-ho** [comment]
Issue has been resolved with the merge #156
