### ISSUE TITLE
Acceptance Test for #3: As a user, I want to be able to get more information about Concordia buildings

### ISSUE THREAD

**Issue by sharon-ho** [felixlapierre/campus-guide#132]
**User Story Covered:**
#3 As a user, I want to be able to get more information about Concordia buildings

**Acceptance Criteria:**
When a user taps on a highlighted Concordia building, a popup appears on the map above that building. The following things should be in the popup:
- The name of the building
- The address of the building
- A list of services in that building
- A "Go Here" button that is used as the destination location for navigation

**Steps for Acceptance Test:**
1. Open the application
2. Wait about 5 seconds - this is a workaround to bug #140 
2. Click on the Hall, Library, or EV building.

Expected: A popup will appear with information about the building including name, address, and list of services.

NOTE: This feature will display placeholder information when clicking any building other than Hall, Library or EV. Additional buildings can be added to the solution without requiring the modification of any code, requiring only data entry. We did not think it necessary to enter every building's information to demonstrate the functionality of the feature.

[**Please refer to this video for a demonstration of this acceptance criteria**](https://drive.google.com/open?id=1G7OGVrHj-ex6uYcFwdXc16bwIO8yFka9)

**Note:**
- Buildings in LOY campus are not highlighted as they are not populated yet in the database, therefore tapping on those buildings will not have info-windows pop-up as info-window pop-ups are dependent on building highlights

**Comment by jodavimehran** [comment]
Accepted
