### ISSUE TITLE
Acceptance Test for #15: As a user, I want to select which calendar to use for retrieving my next event

### ISSUE THREAD

**Issue by gdzooks** [felixlapierre/campus-guide#133]
**User Story Covered:**
#15 As a user, I want to select which calendar to use for retrieving my next event

**Acceptance Criteria:**
Given that I am on the campus map/main view
And that I click the hamburger button in the header
And I am already logged in to my Google account
And I click the Calendar menu item
I should be able to select one of my calendars

**Steps for Acceptance Test:**
1. Open the application
2. Tap on the hamburger menu icon in the header
3. Log into the Google account of your choosing
4. **_Allow_** the request for Calendar permissions or else this feature is not testable
5. Tap on the hamburger menu icon in the header
6. A menu item titled "Calendar" should now be visible in the list
7. Tap on the Calendar menu item
8. Select a calendar from those presented by tapping on one of the calendars displayed in the dialog
9. Tap the "OK" button to confirm the selection

To confirm that the correct calendar has been selected:
* There will be a Toast message that informs you what your calendar has been set to.
* Upon tapping the hamburger menu icon, you should be able to see the name of your selected calendar in the title of the Calendar menu item.

[**Please refer to this video for a demonstration of this acceptance criteria**](https://drive.google.com/open?id=1Fbz8gcy7Qkzk6ORlLWaCxgC7VRG39MHp)

**Comment by jodavimehran** [comment]
accepted
