### ISSUE TITLE
Acceptance Test for #49: As a user, I want to get directions to a building that I tapped on the map

### ISSUE THREAD

**Issue by gdzooks** [felixlapierre/campus-guide#134]
**User Story Covered:**
#49 As a user, I want to get directions to a building that I tapped on the map

**Acceptance Criteria:**
Given that I am on the map page/main view
And that I tap on a building that is highlighted on the map that **_DOES NOT_** have dummy info in its info-window (i.e. Hall Building, LB Building or EV Building ONLY)
And I click the “GO HERE” button in the info-window popup that appears for that building
And that I then enter my start location
Then I should see a route from my start location to the building I tapped earlier appear on the map

**Steps for Acceptance Test:**
1. Open the application
2. Tap on a highlighted building (i.e. Hall Building **_OR_** LB Building **_OR_** EV Building **ONLY**) to trigger the building's info-window pop up
3. Tap on the "GO HERE" button in the info-window pop-up
4. Choose your origin, it is highly recommended that you use the "Search for location" option, as not all other methods are usable as of yet
5. Directions route is now displayed on the map

[**Please refer to this video for a demonstration of this acceptance criteria**](https://drive.google.com/open?id=1GAY_seMgXF9l1wIlWWHqdQg3nMOxNXMK)

**Comment by jodavimehran** [comment]
Accepted
