### ISSUE TITLE
Acceptance Test for #16: As a user, when getting directions, I want my suggested destination to be my next calendar event

### ISSUE THREAD

**Issue by gdzooks** [felixlapierre/campus-guide#135]
**User Story Covered:**
#16 As a user, when getting directions, I want my suggested destination to be my next calendar event

**Acceptance Criteria:**
Given that I am on the map page and I click the directions button, I should be able to select "Use next event" and use that event's location as a destination for my directions. 
Also, given that I have selected a destination, I should be able to then select "Use last event" to use that event's location as an origin for my directions.

**Prerequisite Steps for Acceptance Test:**
1. Follow the acceptance test steps for issue #15, detailed in issue #133 
2. Make sure you have two events today set in the calendar you will be selecting, one before the current time with a location set and another event after the current time with a location set, this is crucial for the feature, otherwise no events will be found. This feature works with indoor locations - such as "LB-385" or "LB-261" - and outdoor locations - such as "Henry F. Hall Building"

**Steps for Acceptance Test:**
1. Tap on the directions button to pull up destination selection options
2. Tap the "Use next event" button to use the next event's location as your destination
3. The screen will switch to the origin/start location selection screen
4. Select the "Use last event" button to use the last event's location as your origin/start location
5. The directions are now displayed on the map

[**Please refer to this video for a demonstration of this acceptance criteria**](https://drive.google.com/open?id=1FyyuFEBQPN8jkGwM7upvo08Faf7OCWEt)

**Notes:**
* If there are no events for the day, a pop up appears to explain this.
* If the location cannot be processed properly yet (e.g. an indoor location), a pop up (different from above) appears to explain this.

**Comment by jodavimehran** [comment]
Accepted
