### ISSUE TITLE
Acceptance Test for #10: As a user, I want to get directions by foot, by car or by public transit

### ISSUE THREAD

**Issue by sharon-ho** [felixlapierre/campus-guide#136]
**User Story Covered:**
#10 As a user, I want to get directions by foot, by car or by public transit

**Acceptance Criteria:**
Given that I am on the maps page
And that I click on the Navigate button at the bottom left of the screen
And that I click on Search for location button
And that I enter any location (ex. Hall Building) as a start location
And that I enter any other location (ex. Grey Nuns Residence) as an end location
Then I should see Car directions appear on the map as the default route with the time it will take.

Given that I click on the Walk icon:
Then I should see walking directions route appear on the map with the time it will take

Given that I click on the Bus icon:
Then I should see bus directions route appear on the map with the time it will take

**Steps for Acceptance Test:**
1. Open the application
2. Click on the Navigate button at the bottom left of the screen
3. Click on Search for location button from the presented options
4. Enter any location (ex. Hall Building) as a start location
5. Enter any other location (ex. Grey Nuns Residence) as an end location
6. The following travel methods will be presented at the top of the screen underneath the start and destination locations listed as coordinates: Car, Walk and Transit
7. The default route displayed on the map is for Car directions with the time it will take displayed next to the Car icon
8. Tapping on the Walk icon will have the walking directions route appear on the map with the time it will take displayed next to the Walk icon
9. Tapping on the Bus icon will have the bus directions route appear on the map with the time it will take displayed next to the Bus icon

[**Please refer to this video for a demonstration of this acceptance criteria**](https://drive.google.com/open?id=1G5jeXdpaK666M6f_F1IATtr1dOHMCZYk)

**Comment by jodavimehran** [comment]
The app should show the path steps from the start point to the endpoint.
The app should show the first step as the current step at the beginning and use a next step button and a previous step button to move between the steps.
In each step, the app should move the map view to the point of the current step.
