### ISSUE TITLE
Acceptance Test for #7: As a user, I want to get directions to the target of my search

### ISSUE THREAD

**Issue by gdzooks** [felixlapierre/campus-guide#137]
**Acceptance Criteria:**
Given that I am on the map page
And that I search for any campus building (ex. Hall Building)
Then my map should center on the building and I should see a popup appear.
Given that I click the “Go Here” button,
and that I enter my start location,
then I should see a route from my start location to the Hall building

**Steps for Acceptance Test:**
1. Open the application
2. Tap on the search icon in the header
3. Type in your search target (ex. "Hall Building")
4. Select the building from the suggested results
5. A pop up appears on the building with the title and address of the building, and a "Confirm" button
6. Tap on the "Confirm" button to confirm this location as your desired destination
7. Tap on one of the options for selecting the origin of your directions, it is highly recommended that you use the "Search for location" option, as not all other methods are usable as of yet
8. The directions route is now displayed on the map

[**Please refer to this video for a demonstration of this acceptance criteria**](https://drive.google.com/open?id=1GTVFZptTffUF5dIrzyFJXnul7W5HGFst)

**Comment by jodavimehran** [comment]
Accepted
