### ISSUE TITLE
Acceptance Test for #29: As a user, I would like to find points of interest on campus that are inside buildings

### ISSUE THREAD

**Issue by sharon-ho** [felixlapierre/campus-guide#138]
**User Story Covered:**
#29 As a user, I would like to find points of interest on campus that are inside buildings

**Acceptance Criteria:**
Given that I am on the map page,
And that I click on the magnifying glass icon on the right of the top bar,
And that I enter “Technology Sandbox”
And that I select the first result in the displayed list
Then I should see a marker appear in the west corner of the LB Building
And I should see the map center itself on this marker
And I should see a popup with the words “Technology Sandbox” and the address of the location appear.

**Steps for Acceptance Test:**
1. Open the application
2. Tap the search icon in the header
3. Search for any room in the LB building 2nd floor or 3rd floor. Some examples: "Technology Sandbox" "LB-385" "Ireland" "Multifunctional Room"
4. Observe the info-window pop-up associated with the searched location

[**Please refer to this video for a demonstration of this acceptance criteria**](https://drive.google.com/open?id=1GR4GcOyi8psuDkwK5xynAAhO0VgK1cBQ)

**Note:**
- Not all indoor locations/points of interests have been populated in the app, therefore to test this feature please **_ONLY_** use locations found inside the LB Building 2nd and 3rd floors. Additional rooms / locations can be added without changing any code, so the feature is considered to be complete. More rooms will be added as part of #20

**Comment by jodavimehran** [comment]
Accepted
