### ISSUE TITLE
Application crashes when getting directions to the target of search

### ISSUE THREAD

**Issue by sharon-ho** [felixlapierre/campus-guide#139]
**Steps to reproduce:**
1. Click on the header icon
2. Enter any location
3. Click confirm in the info-window pop-up
4. Click on search for location button for the start location
5. Notice how the destination name/coordinates have latlng:(...) in its name which I believe is what's causing the crash since it is not able to parse that for navigation directions

**Expected:**
- Directions should be displayed when using a destination location obtained from the header search

**Actual:**
- Destination location obtained from the header search is not parsed properly causing app to crash

**Please refer to this [video](https://drive.google.com/open?id=1GTVFZptTffUF5dIrzyFJXnul7W5HGFst) for clarification!**

**Comment by felixlapierre** [comment]
The bug is not actually caused by a parsing error. It is caused when no route can be found from the start location to the end location.

**Comment by felixlapierre** [comment]
Nevermind, this is caused by using the wrong LatLng type. One of the types has a bad toString that is not recognized by the directions API.
