### ISSUE TITLE
As a user, I want indoor directions to the closest bathroom or water fountain 

### ISSUE THREAD

**Issue by felixlapierre** [felixlapierre/campus-guide#23]
**Acceptance Criteria**
Given that I am on the map page,
And that I click the search icon in the header,
And that I enter a point of interest (e.g. Bathroom)
And that I select one of the suggestions that appear in the search results (e.g. “Women’s Bathroom / Find a bathroom near me”)
And that I select/enter my current location so that the app can find which amenity is nearest,
And a popup appears over the nearest amenity with a “Go Here” button,
And that I click the “Go Here” button,
And that I select my current location for navigation,
Then I should see the directions page with indoor directions to the closest amenity of my choice.

**Mockups:**
![Search for Location - POI.png](https://images.zenhubusercontent.com/5e1cf02ce040605817d94ec2/10fed441-97d1-48d8-b464-8f6e5e9067c2)
![Directions - Navigation – POI](https://user-images.githubusercontent.com/33813045/78205880-51bec180-746b-11ea-87e5-70ba11288da9.png)

**Comment by jun-loke** [comment]
UI-heavy
