### ISSUE TITLE
As a user, I want to see a list of the closest N points of interest

### ISSUE THREAD

**Issue by felixlapierre** [felixlapierre/campus-guide#24]
**Acceptance Criteria**
Given that I am on the maps page,
And that I have my current location centered,
And that I click on “Near Me” in the bottom navigation bar,
And that I choose any of the options presented,
I should see markers appear of selected nearby points of interest.

**Comment by jun-loke** [comment]
Points of interest meaning coffee shop, restaurant, etc
Exists in gmaps search api
