### ISSUE TITLE
As a user, I want to be able to get more information about Concordia buildings

### ISSUE THREAD

**Issue by felixlapierre** [felixlapierre/campus-guide#3]
**Acceptance Criteria:**
When a user taps on a Concordia building, a popup appears on the map above that building. The following things should be in the popup:
- The name of the building
- The address of the building
- An X button to close the popup
- A description of the building
- A "Go Here" button that does nothing

**Mockup Flow:**
![S1 - UC-3 Building Info - Tap.png](https://images.zenhubusercontent.com/5e1cf02ce040605817d94ec2/4f83ae10-214a-4aba-a5fc-7f20cc97697e)

**Comment by felixlapierre** [comment]
For 1st iteration: Minimum requirement is getting that popup so we can put a "go here" button

Feature completion: Display info about buildings for all the buildings (data entry / writing / local database)

**Comment by FGRCL** [comment]
I think the easiest way to do yhis is modify my highlights a little bit. Hmu if you want some info.
