### ISSUE TITLE
User Interface Design

### ISSUE THREAD

**Issue by felixlapierre** [felixlapierre/campus-guide#38]
https://github.com/arejayelle/Campus-guide-Mockups/

- [x] Personas
- - [x] Student
- - [x] Faculty
- - [x] Staff
- - [x] Visitors
- - [x] User with disability
- [x] UI mockups for user stories (Certain personas might have mockups dedicated to adapting to their user behavior)
- - [x] [Map epic](https://drive.google.com/drive/folders/1jzaznRP25jrGh9JxpoCsW0M83jUj2-C_)
- - [x] Indoor locations epic
- - [x] Outdoor locations epic
- - [x] POI epic
- [x] Comment on quality, ease of use and error tolerance

**Comment by sharon-ho** [comment]
- [ ] Personas
- [ ] UI Mockups for User Stories
- [ ] Comment on quality, ease of use and error tolerance

**Comment by sharon-ho** [comment]
https://uxplanet.org/creating-free-sketch-templates-user-personas-journey-maps-541df39d3f1b
https://xtensio.com/user-persona/
https://www.justinmind.com/blog/user-persona-templates/
