### ISSUE TITLE
Directions user flow does not match mockups

### ISSUE THREAD

**Issue by felixlapierre** [felixlapierre/campus-guide#55]
**Issues:**
- Navigation button on main page does not have the correct appearance and is not in the right location
- After clicking navigation, most of the buttons are missing, instead asking the user to enter a start and end destination which does not suggest locations
- Once displaying directions, the start and end locations are not displayed, and there is no Back button to close the directions

![Where are you now mockup](https://user-images.githubusercontent.com/32281260/75289778-07538080-57ed-11ea-9e83-20e033c46639.png)

![Display directions mockup](https://user-images.githubusercontent.com/32281260/75289818-1cc8aa80-57ed-11ea-80f7-45b8e45a94a6.png)

**Comment by sharon-ho** [comment]
@felixlapierre Suggested fixes for the description of this bug:
> **Issues:**
> - Navigation button on main page does not have the correct appearance and is not in the right location (i.e. is not found in a menu bar at the bottom and has the wrong icon) 
> - The user needs to enter a start and end destination all at the same time, instead of having separate views for inputting/selecting start and end destination
> - When inputting a location, there are no locations suggested while typing
> - Once displaying directions, the start and end locations are not displayed, and there is no Back button to close the directions
